import {
  orangeProduct1,
  orangeProduct2,
  orangeProduct3,
  orangeProduct4,
  blueProduct1,
  blueProduct2,
  blueProduct3,
  grayProduct1,
  grayProduct2,
  grayProduct3,
  grayProduct4,
  purpleProduct1,
  purpleProduct2,
  purpleProduct3,
  purpleProduct4,
  brownProduct1,
  brownProduct2,
  brownProduct3,
  brownProduct4,
  brownProduct5,
  yellowProduct1,
  yellowProduct2,
  yellowProduct3,
  yellowProduct4,
  yellowProduct5,
  redProduct1,
  redProduct2,
  redProduct3,
  whiteProduct1,
  whiteProduct2,
  whiteProduct3,
  whiteProduct4,
  whiteProduct5,
  greenProduct1,
  greenProduct2,
  greenProduct3,
  greenProduct4,
  blackProduct1,
  blackProduct2,
  blackProduct3,
  blackProduct4,
  pinkProduct1,
  pinkProduct2,
  pinkProduct3,
  pinkProduct4,
} from '../assets';


const products = [
  {
    id: 1,
    name: 'Air Max 90 Black Edition',
    description: 'The Air Max 90 in black offers a sleek, modern look with breathable mesh and durable leather. Designed for both style and comfort, these sneakers provide a cushioned sole for a smooth walking experience.',
    price: 120,
    image: blackProduct1,
    images: [blackProduct1, blackProduct2, blackProduct3, blackProduct4],
  },
  {
    id: 2,
    name: 'Nike Air Force 1 White Classic',
    description: 'A timeless design, the Nike Air Force 1 in white features a premium leather upper for durability and comfort. The cushioned midsole offers support for all-day wear, making it a versatile addition to any wardrobe.',
    price: 110,
    image: whiteProduct2,
    images: [whiteProduct1, whiteProduct2, whiteProduct3, whiteProduct4, whiteProduct5],
  },
  {
    id: 3,
    name: 'Adidas UltraBoost Red Limited',
    description: 'Engineered for performance, the Adidas UltraBoost Red Limited offers energy-returning cushioning for maximum comfort. The breathable knit upper and responsive midsole make this sneaker ideal for long-lasting wear and support.',
    price: 180,
    image: redProduct1,
    images: [redProduct1, redProduct2, redProduct3],
  },
  {
    id: 4,
    name: 'Puma RS-X Blue Neon',
    description: 'Puma RS-X Blue Neon features a bold, futuristic design with premium materials. The multi-layered upper provides both durability and breathability, while the thick sole ensures superior cushioning and comfort.',
    price: 130,
    image: blueProduct1,
    images: [blueProduct1, blueProduct2, blueProduct3],
  },
  {
    id: 5,
    name: 'Reebok Classic Leather Brown',
    description: 'The Reebok Classic Leather in brown combines a retro design with premium leather and a soft foam midsole for everyday comfort. Its durable rubber outsole provides excellent grip, perfect for both casual and athletic wear.',
    price: 100,
    image: brownProduct1,
    images: [brownProduct1, brownProduct2, brownProduct3, brownProduct4, brownProduct5],
  },
  {
    id: 6,
    name: 'New Balance 990 Green Edition',
    description: 'The New Balance 990 Green Edition combines superior craftsmanship with premium cushioning for a luxurious fit. The supportive design provides long-lasting comfort, while the clean green colorway adds a fresh and stylish touch to your collection.',
    price: 160,
    image: greenProduct2,
    images: [greenProduct1, greenProduct2, greenProduct3, greenProduct4],
  },
  {
    id: 7,
    name: 'Converse Chuck Taylor Yellow',
    description: 'A modern take on a classic high-top design, the Converse Chuck Taylor in yellow delivers a bold statement. With its durable canvas upper and cushioned insole, it remains comfortable and stylish, perfect for everyday wear.',
    price: 60,
    image: yellowProduct1,
    images: [yellowProduct1, yellowProduct2, yellowProduct3, yellowProduct4, yellowProduct5],
  },
  {
    id: 8,
    name: 'Vans Old Skool Purple',
    description: 'Vans Old Skool in purple showcases the brand’s signature style with its iconic low-top silhouette. The purple suede and canvas upper provide a sleek, comfortable fit, while the padded collar and durable rubber sole add to its legendary comfort.',
    price: 70,
    image: purpleProduct3,
    images: [purpleProduct1, purpleProduct2, purpleProduct3, purpleProduct4],
  },
  {
    id: 9,
    name: 'Under Armour HOVR Phantom Pink',
    description: 'The Under Armour HOVR Phantom in pink is designed for maximum performance and comfort. Featuring responsive cushioning, a breathable upper, and a durable outsole, this sneaker provides long-lasting support for athletes and casual wearers alike.',
    price: 140,
    image: pinkProduct4,
    images: [pinkProduct1, pinkProduct2, pinkProduct3, pinkProduct4],
  },
  {
    id: 10,
    name: 'ASICS Gel-Kayano Gray',
    description: 'The ASICS Gel-Kayano in gray is built for stability and comfort. With a cushioned midsole, durable rubber outsole, and a supportive upper, these shoes offer excellent comfort for runners or anyone on their feet for extended periods.',
    price: 120,
    image: grayProduct1,
    images: [grayProduct1, grayProduct2, grayProduct3, grayProduct4],
  },
  {
    id: 11,
    name: 'Nike Air VaporMax Plus',
    description: 'The Nike Air VaporMax Plus blends the past and future with a modernized Air cushioning system and a classic design. Featuring a snug fit, durable outsole, and a sleek orange finish, this sneaker is perfect for style and comfort enthusiasts.',
    price: 200,
    image: orangeProduct1,
    images: [orangeProduct1, orangeProduct2, orangeProduct3, orangeProduct4],
  },
];

export default products;
